#!/usr/bin/env python3
"""Bake a .krnn into MLRift source, for freestanding MCU images.

    krnn_to_mlr.py <model.krnn> <out.mlr> [--sym nn_blob] [--per 1500]

On the host the runner just reads the .krnn from a file. A freestanding
xtensa/riscv32 image has no filesystem, so the model has to be in the image.

WHY store32 STATEMENTS AND NOT A DATA LITERAL
---------------------------------------------
MLRift has no `include_bytes`, and the two obvious alternatives do not reach:

  * string literals: the compiler's whole-program string pool is capped at
    65536 bytes (codegen.mlr "str_buf overflow"), and even a hex encoding
    would need 2x the model size. YuNet@128 is 89304 bytes.
  * `static u8[N] x = [...]`: MLRift array statics have no initialiser list;
    only scalars can carry one.

So the model is emitted as a run of store32 calls into a zero-initialised
static. Two constraints shape the output:

  * ir.mlr caps a function at 65536 IR instructions, and the xtensa backend
    rejects a stack frame over 32752 bytes -- one vreg per constant means a
    long function spills into an enormous frame. 1500 stores per function
    stays comfortably under both. Measured: 2000 works, 6000 does not.
  * .bss is zero on entry (verified on qemu lx60 and riscv32 virt), so zero
    words are skipped entirely.

The result is large -- roughly 20 bytes of code per 4 bytes of model -- which
is fine for a qemu image and is NOT how you would ship this on real silicon.
There the .krnn belongs in a flash partition at a fixed address, and the
runner takes that address directly: nn_model_run() never assumes the model is
writable or that it lives anywhere in particular.
"""
import argparse, struct, sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("krnn")
    ap.add_argument("out")
    ap.add_argument("--sym", default="nn_blob")
    ap.add_argument("--per", type=int, default=1500)
    args = ap.parse_args()

    data = open(args.krnn, "rb").read()
    if len(data) % 4:
        data += b"\0" * (4 - len(data) % 4)
    words = struct.unpack(f"<{len(data)//4}I", data)
    nz = [(i, v) for i, v in enumerate(words) if v]

    S = args.sym
    L = [f"// GENERATED by tools/ml/krnn_to_mlr.py from {args.krnn}",
         f"// {len(data):,} bytes, {len(nz):,} non-zero words of {len(words):,}.",
         "// Do not edit; regenerate.",
         "",
         f"static u8[{len(data)}] {S}_model",
         "",
         f"fn {S}_model_p() -> u32 {{",
         f"    return {S}_model",
         "}",
         "",
         f"fn {S}_model_n() -> u32 {{",
         f"    u32 v = {len(data)}",
         "    return v",
         "}",
         ""]

    nfn = 0
    for start in range(0, len(nz), args.per):
        chunk = nz[start:start + args.per]
        L.append(f"fn {S}_fill{nfn}() {{")
        L.append(f"    u32 p = {S}_model")
        for i, v in chunk:
            L.append(f"    store32(p + {i * 4}, {v})")
        L.append("}")
        L.append("")
        nfn += 1

    L.append(f"fn {S}_fill() {{")
    for k in range(nfn):
        L.append(f"    {S}_fill{k}()")
    L.append("}")
    L.append("")

    open(args.out, "w").write("\n".join(L))
    print(f"  {args.krnn} -> {args.out}: {len(data):,} bytes as "
          f"{len(nz):,} store32 in {nfn} functions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
